resilience4j.timelimiter:
  instances:
    commentService:
      timeoutDuration: 2s
      cancelRunningFuture: true
    someOtherService:
      timeoutDuration: 1s
      cancelRunningFuture: false

comment:
  service:
    endpoint: http://localhost:8080/comments/